use codestory_contracts::api::{
    AgentAnswerDto, AgentCitationDto, AgentPacketDto, AgentRetrievalPolicyModeDto,
    AgentRetrievalPresetDto, AgentRetrievalTraceDto, CorePromotionTimings,
    DatabaseSnapshotCopyTimings, EdgeId, EdgeKind, FullRefreshWallTimings, GraphArtifactDto,
    GraphEdgeDto, GraphNodeDto, IndexingPhaseTimings, NodeDetailsDto, NodeId, NodeKind,
    PacketBudgetDto, PacketBudgetLimitsDto, PacketBudgetModeDto, PacketBudgetUsageDto,
    PacketClaimDto, PacketPlanDto, PacketPlanQueryDto, PacketRetrievalTraceSummaryDto,
    PacketSufficiencyDto, PacketSufficiencyStatusDto, PacketTaskClassDto, ProjectSummary,
    ProjectionPersistenceFamilyTimings, ProjectionPersistenceTimings, RetrievalModeDto,
    RetrievalStateDto, SearchHit, SearchHitOrigin, SemanticModeDto, StorageStatsDto,
};

pub(super) fn sample_retrieval() -> RetrievalStateDto {
    RetrievalStateDto {
        mode: RetrievalModeDto::Hybrid,
        hybrid_configured: true,
        semantic_ready: true,
        semantic_mode: SemanticModeDto::Enabled,
        semantic_doc_count: 42,
        embedding_model: Some("sentence-transformers/all-MiniLM-L6-v2-local".to_string()),
        current_embedding: None,
        stored_embedding: None,
        fallback_reason: None,
        fallback_message: None,
    }
}

pub(super) fn sample_agent_answer_with_graph(graph: GraphArtifactDto) -> AgentAnswerDto {
    AgentAnswerDto {
        answer_id: "context-test".to_string(),
        prompt: "capped_bundle".to_string(),
        summary: "Bundle summary".to_string(),
        freshness: None,
        sections: Vec::new(),
        citations: Vec::new(),
        subgraph_ids: vec!["big-mermaid".to_string()],
        retrieval_version: "test".to_string(),
        graphs: vec![graph],
        retrieval_trace: AgentRetrievalTraceDto {
            request_id: "context-test".to_string(),
            retrieval_publication: None,
            resolved_profile: AgentRetrievalPresetDto::Architecture,
            policy_mode: AgentRetrievalPolicyModeDto::LatencyFirst,
            total_latency_ms: 1,
            sla_target_ms: None,
            sla_missed: false,
            semantic_fallback_count: 0,
            semantic_fallbacks: Vec::new(),
            annotations: Vec::new(),
            steps: Vec::new(),
            packet_sidecar_diagnostics: Vec::new(),
            retrieval_shadow: None,
        },
    }
}

pub(super) fn sample_task_brief_packet() -> AgentPacketDto {
    let source = sample_task_brief_citation(
        "run_`packet_$env:SECRET$('x')",
        NodeKind::FUNCTION,
        "crates/codestory-cli/src/`main_$env:SECRET$('x').rs",
        1053,
    );
    let test = sample_task_brief_citation(
        "packet_tool_returns_budgeted_sufficiency_contract",
        NodeKind::FUNCTION,
        "crates/codestory-cli/tests/stdio`$env:SECRET$('x')_protocol_contracts.rs",
        2909,
    );
    AgentPacketDto {
            packet_id: "packet-task-brief".to_string(),
            question: "Add `$env:SECRET $(Get-ChildItem) 'literal' task brief".to_string(),
            task_class: Some(PacketTaskClassDto::EditPlanning),
            plan: PacketPlanDto {
                task_class: PacketTaskClassDto::EditPlanning,
                inferred_task_class: false,
                queries: vec![PacketPlanQueryDto {
                    query: "task brief packet surface".to_string(),
                    purpose: "find packet entry points".to_string(),
                }],
                probe_resolutions: Vec::new(),
                trace: Vec::new(),
            },
            answer: AgentAnswerDto {
                answer_id: "answer-task-brief".to_string(),
                prompt: "Add `$env:SECRET $(Get-ChildItem) 'literal' task brief".to_string(),
                summary: "Use the packet command path.".to_string(),
                freshness: None,
                sections: Vec::new(),
                citations: vec![source.clone(), test.clone()],
                subgraph_ids: Vec::new(),
                retrieval_version: "sidecar".to_string(),
                graphs: Vec::new(),
                retrieval_trace: AgentRetrievalTraceDto {
                    request_id: "trace-task-brief".to_string(),
                    retrieval_publication: None,
                    resolved_profile: AgentRetrievalPresetDto::Architecture,
                    policy_mode: AgentRetrievalPolicyModeDto::LatencyFirst,
                    total_latency_ms: 1,
                    sla_target_ms: None,
                    sla_missed: false,
                    semantic_fallback_count: 0,
                    semantic_fallbacks: Vec::new(),
                    annotations: Vec::new(),
                    steps: Vec::new(),
                    packet_sidecar_diagnostics: Vec::new(),
                    retrieval_shadow: None,
                },
            },
            budget: PacketBudgetDto {
                requested: PacketBudgetModeDto::Compact,
                limits: PacketBudgetLimitsDto {
                    max_anchors: 8,
                    max_files: 8,
                    max_snippets: 4,
                    max_trail_edges: 12,
                    max_output_bytes: 32_000,
                },
                used: PacketBudgetUsageDto {
                    anchors: 2,
                    files: 2,
                    snippets: 0,
                    trail_edges: 0,
                    output_bytes: 1024,
                },
                truncated: false,
                omitted_sections: Vec::new(),
                next_deeper_command: None,
            },
            sufficiency: PacketSufficiencyDto {
                status: PacketSufficiencyStatusDto::Partial,
                covered_claims: vec![PacketClaimDto {
                    claim: "Packet command is the starting point.".to_string(),
                    proof_status: None,
                    required_evidence_role: None,
                    citations: vec![source, test],
                    coverage_role: None,
                    eligible_for_sufficiency: None,
                }],
                open_next: Vec::new(),
                avoid_opening: Vec::new(),
                avoid_opening_paths: Vec::new(),
                gaps: vec!["verify `changed` files after editing".to_string()],
                follow_up_commands: vec![
                    "codestory-cli retrieval index --project . --profile agent --refresh auto --format json"
                        .to_string(),
                ],
                coverage_report: None,
            },
            retrieval_trace_summary: PacketRetrievalTraceSummaryDto {
                retrieval_trace: AgentRetrievalTraceDto {
                    request_id: "trace-task-brief".to_string(),
                    retrieval_publication: None,
                    resolved_profile: AgentRetrievalPresetDto::Architecture,
                    policy_mode: AgentRetrievalPolicyModeDto::LatencyFirst,
                    total_latency_ms: 1,
                    sla_target_ms: None,
                    sla_missed: false,
                    semantic_fallback_count: 0,
                    semantic_fallbacks: Vec::new(),
                    annotations: Vec::new(),
                    steps: Vec::new(),
                    packet_sidecar_diagnostics: Vec::new(),
                    retrieval_shadow: None,
                },
                source_read_steps: 0,
                search_steps: 1,
                trail_steps: 0,
            },
        }
}

pub(super) fn sample_task_brief_citation(
    display_name: &str,
    kind: NodeKind,
    file_path: &str,
    line: u32,
) -> AgentCitationDto {
    AgentCitationDto {
        node_id: NodeId(format!("{file_path}:{line}")),
        display_name: display_name.to_string(),
        kind,
        file_path: Some(file_path.to_string()),
        line: Some(line),
        score: 1.0,
        origin: SearchHitOrigin::IndexedSymbol,
        resolvable: true,
        subgraph_id: None,
        evidence_edge_ids: Vec::new(),
        retrieval_score_breakdown: None,
        evidence_tier: None,
        evidence_producer: None,
        resolution_status: None,
        loss_reason: None,
        coverage_role: None,
        eligible_for_sufficiency: None,
    }
}

pub(super) fn summary_with_files(file_count: u32) -> ProjectSummary {
    ProjectSummary {
        root: "C:/repo".to_string(),
        stats: StorageStatsDto {
            node_count: file_count.saturating_mul(10),
            edge_count: 0,
            file_count,
            error_count: 0,
            fatal_error_count: 0,
        },
        members: Vec::new(),
        retrieval: None,
        freshness: None,
        publication: None,
    }
}

pub(super) fn sample_phase_timings() -> IndexingPhaseTimings {
    IndexingPhaseTimings {
        parse_index_ms: 10,
        projection_flush_ms: 20,
        edge_resolution_ms: 30,
        error_flush_ms: 4,
        cleanup_ms: 5,
        full_refresh_wall: Some(FullRefreshWallTimings {
            core_refresh_ms: 1_000,
            live_inspection_ms: 10,
            source_discovery_ms: 20,
            stage_open_ms: 30,
            indexer_execution_ms: 400,
            coverage_validation_ms: 40,
            copy_forward_ms: 50,
            semantic_stage_ms: 150,
            snapshot_stage_ms: 100,
            publication_prepare_ms: 50,
            search_generation_ms: 100,
            catalog_publication_ms: 30,
            unattributed_ms: 20,
        }),
        source_prepare_ms: Some(41),
        projection_batch_wall_ms: Some(50),
        projection_batch_transactions: Some(2),
        projection_persistence: Some(ProjectionPersistenceTimings {
            transactions: 2,
            row_attempts: 40,
            bound_bytes: 4096,
            statement_executions: 35,
            transaction_wall_ms: 48,
            transaction_setup_ms: 1,
            commit_ms: 7,
            files: ProjectionPersistenceFamilyTimings {
                row_attempts: 4,
                bound_bytes: 512,
                statement_executions: 4,
                wall_ms: 3,
            },
            dirty_state: ProjectionPersistenceFamilyTimings {
                row_attempts: 8,
                bound_bytes: 96,
                statement_executions: 8,
                wall_ms: 2,
            },
            ..Default::default()
        }),
        artifact_cache_write_ms: Some(6),
        artifact_cache_writes: Some(24),
        artifact_cache_write_transactions: Some(1),
        parser_artifact_cache: None,
        structural_artifact_cache: None,
        full_refresh_chunks_produced: Some(2),
        full_refresh_chunks_persisted: Some(2),
        full_refresh_queue_capacity: Some(1),
        full_refresh_queue_high_water: Some(1),
        full_refresh_producer_blocked_ms: Some(3),
        full_refresh_writer_idle_ms: Some(4),
        full_refresh_chunk_target_bytes: Some(8_388_608),
        full_refresh_chunk_target_nodes: Some(120_000),
        full_refresh_chunk_file_ceiling: Some(512),
        full_refresh_chunk_max_files: Some(384),
        full_refresh_chunk_max_planned_bytes: Some(7_500_000),
        full_refresh_chunk_max_nodes: Some(98_000),
        full_refresh_chunk_budget_overruns: Some(0),
        full_refresh_chunk_planning_ms: Some(5),
        cache_refresh_ms: Some(6),
        search_projection_rebuild_ms: Some(61),
        search_symbol_stream_ms: Some(60),
        search_symbol_stream_rows: Some(8192),
        search_symbol_stream_batches: Some(2),
        search_symbol_index_ms: Some(62),
        search_symbol_index_docs_written: Some(8192),
        search_symbol_index_writer_count: Some(1),
        search_symbol_index_commit_count: Some(1),
        search_symbol_index_commit_ms: Some(64),
        search_symbol_index_reload_count: Some(1),
        search_symbol_index_reload_ms: Some(65),
        runtime_cache_publish_ms: Some(63),
        semantic_context_index_ms: Some(59),
        semantic_node_load_ms: Some(66),
        semantic_node_load_rows: Some(8_192),
        semantic_node_stream_batches: Some(2),
        semantic_endpoint_load_ms: Some(6),
        semantic_endpoint_load_rows: Some(4_096),
        semantic_endpoint_load_batches: Some(21),
        semantic_selected_nodes: Some(2_048),
        semantic_context_file_count: Some(128),
        semantic_context_path_bytes: Some(16_384),
        semantic_node_lookup_entries: Some(8_192),
        semantic_context_ms: Some(67),
        semantic_doc_build_ms: Some(7),
        semantic_embedding_ms: Some(8),
        semantic_db_upsert_ms: Some(9),
        semantic_reload_ms: Some(10),
        semantic_prune_ms: Some(64),
        semantic_docs_reused: Some(11),
        semantic_docs_embedded: Some(12),
        semantic_docs_pending: Some(13),
        semantic_docs_stale: Some(14),
        symbol_search_docs_written: Some(15),
        semantic_dense_docs_skipped: Some(16),
        semantic_dense_public_api: Some(17),
        semantic_dense_entrypoint: Some(18),
        semantic_dense_documented_nontrivial: Some(19),
        semantic_dense_central_graph_node: Some(20),
        semantic_dense_component_report: Some(21),
        semantic_dense_unstructured_doc: Some(22),
        deferred_indexes_ms: Some(7),
        summary_snapshot_ms: Some(8),
        detail_snapshot_ms: Some(9),
        publish_ms: Some(10),
        staged_sqlite_wal_autocheckpoint_bytes: Some(67_108_864),
        staged_sqlite_checkpoint_ms: Some(11),
        staged_sqlite_sync_ms: Some(12),
        staged_snapshot_copy: Some(DatabaseSnapshotCopyTimings {
            copy_ms: 13,
            source_bytes: 1_024,
            target_bytes: 1_024,
        }),
        core_promotion: Some(CorePromotionTimings {
            total_ms: 89,
            lock_recovery_ms: 1,
            candidate_validation_ms: 11,
            previous_validation_ms: 12,
            rollback_backup_copy_ms: Some(13),
            backup_validation_ms: Some(14),
            prepared_journal_write_ms: 2,
            prepared_journal_file_sync_ms: 3,
            prepared_journal_directory_sync_ms: 4,
            staged_to_live_restore_ms: 15,
            promoted_validation_ms: 10,
            committed_journal_ms: 2,
            cleanup_ms: 1,
            unattributed_ms: 1,
            candidate_bytes: 2_048,
            previous_live_bytes: Some(1_024),
            rollback_backup_bytes: Some(1_024),
        }),
        setup_existing_projection_ids_ms: Some(11),
        setup_seed_symbol_table_ms: Some(12),
        flush_files_ms: Some(13),
        flush_nodes_ms: Some(14),
        flush_edges_ms: Some(15),
        flush_occurrences_ms: Some(16),
        flush_component_access_ms: Some(17),
        flush_callable_projection_ms: Some(18),
        unresolved_calls_start: 19,
        unresolved_imports_start: 20,
        resolved_calls: 21,
        resolved_imports: 22,
        unresolved_calls_end: 23,
        unresolved_imports_end: 24,
        resolution_override_count_ms: Some(25),
        resolution_unresolved_counts_ms: Some(26),
        resolution_calls_ms: Some(27),
        resolution_imports_ms: Some(28),
        resolution_cleanup_ms: Some(29),
        resolution_call_candidate_index_ms: Some(30),
        resolution_import_candidate_index_ms: Some(31),
        resolution_call_semantic_index_ms: Some(32),
        resolution_import_semantic_index_ms: Some(33),
        resolution_support_snapshot_limit_bytes: Some(1_000_000_000),
        resolution_support_snapshot_stored: Some(true),
        resolution_support_snapshot_skipped_oversize: Some(false),
        resolution_call_semantic_candidates_ms: Some(34),
        resolution_import_semantic_candidates_ms: Some(35),
        resolution_call_semantic_requests: Some(36),
        resolution_call_semantic_unique_requests: Some(37),
        resolution_call_semantic_skipped_requests: Some(38),
        resolution_import_semantic_requests: Some(39),
        resolution_import_semantic_unique_requests: Some(40),
        resolution_import_semantic_skipped_requests: Some(41),
        resolution_call_compute_ms: Some(42),
        resolution_import_compute_ms: Some(43),
        resolution_call_apply_ms: Some(44),
        resolution_import_apply_ms: Some(45),
        resolution_override_resolution_ms: Some(46),
        resolved_calls_same_file: Some(47),
        resolved_calls_same_module: Some(48),
        resolved_calls_global_unique: Some(49),
        resolved_calls_semantic: Some(50),
        resolved_imports_same_file: Some(51),
        resolved_imports_same_module: Some(52),
        resolved_imports_global_unique: Some(53),
        resolved_imports_fuzzy: Some(54),
        resolved_imports_semantic: Some(55),
    }
}

pub(super) fn sample_node_details(id: &str, display_name: &str) -> NodeDetailsDto {
    NodeDetailsDto {
        id: NodeId(id.to_string()),
        kind: codestory_contracts::api::NodeKind::FUNCTION,
        display_name: display_name.to_string(),
        serialized_name: display_name.to_string(),
        qualified_name: None,
        canonical_id: None,
        file_path: None,
        start_line: None,
        start_col: None,
        end_line: None,
        end_col: None,
        member_access: None,
        route_endpoint: None,
        evidence_tier: None,
        evidence_producer: None,
        resolution_status: None,
    }
}

pub(super) fn sample_graph_node(id: &str, label: &str) -> GraphNodeDto {
    GraphNodeDto {
        id: NodeId(id.to_string()),
        label: label.to_string(),
        kind: codestory_contracts::api::NodeKind::FUNCTION,
        depth: 0,
        label_policy: None,
        badge_visible_members: None,
        badge_total_members: None,
        merged_symbol_examples: Vec::new(),
        file_path: None,
        qualified_name: None,
        member_access: None,
    }
}

pub(super) fn sample_graph_edge(
    id: &str,
    source: &str,
    target: &str,
    certainty: Option<&str>,
) -> GraphEdgeDto {
    sample_graph_edge_with_kind(id, source, target, EdgeKind::CALL, certainty)
}

pub(super) fn sample_graph_edge_with_kind(
    id: &str,
    source: &str,
    target: &str,
    kind: EdgeKind,
    certainty: Option<&str>,
) -> GraphEdgeDto {
    GraphEdgeDto {
        id: EdgeId(id.to_string()),
        source: NodeId(source.to_string()),
        target: NodeId(target.to_string()),
        kind,
        confidence: None,
        certainty: certainty.map(ToOwned::to_owned),
        callsite_identity: None,
        candidate_targets: Vec::new(),
    }
}

pub(super) fn test_search_hit_defaults() -> SearchHit {
    SearchHit {
        node_id: NodeId(String::new()),
        display_name: String::new(),
        kind: NodeKind::UNKNOWN,
        file_path: None,
        line: None,
        score: 0.0,
        origin: codestory_contracts::api::SearchHitOrigin::IndexedSymbol,
        match_quality: None,
        resolvable: true,
        evidence_tier: None,
        evidence_producer: None,
        resolution_status: None,
        loss_reason: None,
        coverage_role: None,
        eligible_for_sufficiency: None,
        source_excerpt: None,
        verification_targets: Vec::new(),
        score_breakdown: None,
    }
}
